config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "cats#index"

  resources :cats, except: :destroy do
    resources :cat_rental_requests, only: [:new]
  end
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :username, :password_digest, :session_token, presence: true, uniqueness: true
    before_validation :ensure_session_token
    validates :password, length:{minimum: 6, allow_nil: true}

    attr_reader :password

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil if user.nil?
        user && user.is_password?(password) ? user : nil
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end

    private

    def generate_unique_session_token
        loop do 
            session_token = SecureRandom::urlsafe_base64(16)
            return session_token unless User.exists?(session_token: session_token)
        end
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_out

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to cats_url
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/views/users/new.html.erb
<section class="page">
  <div class="centered-box">
    <h1>New User</h1>

    <%= render 'shared/errors' %>

    <form action="<%= users_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <label for="user_username">Username: </label>
      <input type="text"
        name="user[username]"
        id="user_username"
        value="<%= @user.username %>">
      <br>

      <label for="user_password">Password: </label>
      <input type="password"
        name="user[password]"
        id="user_password"
        value="<%= @user.password %>">
      <br>

      <input type="submit" value="Sign up!">
    </form>
  </div>
</section>