config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "cats#index"

  resources :cats, except: :destroy do
    resources :cat_rental_requests, only: [:new]
  end
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  # .freeze renders a constant immutable.
  CAT_COLORS = %w[black white orange brown].freeze

  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: %w[M F]
  # Note that you don't need to validate `color` or `sex` for presence because
  # NULL values for those columns will fail the inclusion tests.
  validates :birth_date, :name, presence: true
  validate :birth_date_cannot_be_future

  # Remember: `has_many` is just a method where the first argument is the name
  # of the association and the second argument is an options hash.
  has_many :rental_requests,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def birth_date_cannot_be_future
    # Must check that birth_date is present because `>` will crash if run on
    # `nil`
    return unless birth_date.present? && birth_date > Date.today

    errors.add(:birth_date, "can't be in the future")
  end

  def age
    time_ago_in_words(birth_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :description, :name, :sex)
  end
end

app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :PATCH : :POST) %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">
  <label for="cat_name">Name</label>
  <input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%= cat.name %>"
  >
  <br>

  <label for="cat_birth_date">Birth date</label>
  <input
    type="date"
    name="cat[birth_date]"
    id="cat_birth_date"
    value="<%= cat.birth_date %>"
  >
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option disabled selected>-- select a color --</option>
      <% Cat::CAT_COLORS.each do |color| %>
        <option
          <%= cat.color == color ? "selected" : "" %>
          value="<%= color %>">
          <%= color.upcase %>
        </option>
      <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>
  >
  <label for="cat_sex_male">Male</label>
  <input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>
  >
  <label for="cat_sex_female">Female</label>
  <br>

  <label>
    Description
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>

  <br>
  <% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/cats/_req_tr.html.erb
<tr>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td>
    <% if req.pending? %>
      <form action="<%= approve_cat_rental_request_url(req) %>" method="post">
        <input type="submit" value="Approve">
      </form>
      <form action="<%= deny_cat_rental_request_url(req) %>" method="post">
        <input type="submit" value="Deny">
      </form>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

app/views/cats/edit.html.erb
<section class="page"><div class="centered-box">
  <h1>Edit My Cat</h1>
  <%= render 'shared/errors' %>
  <%= render 'form', cat: @cat %>
</div></section>

app/views/cats/index.html.erb
<section class="cat-index-holder">
  <nav>
    <h1>ALL THE CATS IN THE WORLD</h1>
    <a href="<%= new_cat_url %>">
      Add Cat
      <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
    <a href="<%= new_cat_rental_request_url %>">
      Request a Rental
      <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
  </nav>
  <section class="cat-index">
    <% @cats.each do |cat| %>
      <div class="cat-index-item">
        <div>
          <img src="http://placekitten.com/g/231/231" >
          <br /><a href="<%= cat_url(cat) %>">Rent <%= cat.name %></a>
        </div>
      </div>
    <% end %>
  </section>
</section>

app/views/cats/new.html.erb
<section class="page"><div class="centered-box">
  <h1>New Cat</h1>
  <%= render 'shared/errors' %>
  <%= render 'form', cat: @cat %>
</div></section>

app/views/cats/show.html.erb
<section class="page"><div class="centered-box">
  <img src="http://placekitten.com/g/300/300" >
  <h1><%= @cat.name %></h1>

  <table>
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>
    <% [:age, :birth_date, :color, :sex].each do |attr_name| %>
      <tr>
        <td><%= attr_name %></td>
        <td><%= @cat.send(attr_name) %></td>
      </tr>
    <% end %>
    <% if @cat.description.present? %>
      <tr>
        <th colspan="2">Description</th>
      </tr>
      <tr>
        <td colspan="2"><%= @cat.description %></td>
      </tr>
    <% end %>
  </table>

  <a href="<%= edit_cat_url(@cat) %>">Edit <%= @cat.name %></a>

  <br><br>
  <h1>Rental Requests</h1>
  <% if @cat.rental_requests.empty? %>
    <p><%= @cat.name %> has no rental requests.</p>
  <% else %>
    <table>
      <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
      </tr>
      <% @cat.rental_requests.order('start_date').each do |req| %>
        <%= render 'req_tr', req: req %>
      <% end %>
    </table>
  <% end %>
  <a href="<%= new_cat_cat_rental_request_url(@cat) %>">
    Request a Rental
  </a>
</div></section>