config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "cats#index"

  resources :cats, except: :destroy do
    resources :cat_rental_requests, only: [:new]
  end
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>99 Cats</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <nav class="main-nav">
      <h1><a href="<%= cats_url %>">99 Cats</a></h1>
      <% if current_user.nil? %>
        <a href="<%= new_user_url %>">Sign up!</a> 
        <a href="<%= new_session_url %>">Sign in!</a>≈
        <% else %>
        <%= current_user.username %>
        <form action="<%= session_url %>" method="POST">
          <input type="hidden" 
            name="authenticity_token" 
            value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="DELETE">
          <input type="submit" value="logout">
        </form>  
  <% end %>    
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>